# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-19 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionService', '0024_auto_20190314_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=150)),
                ('row_data', models.TextField()),
                ('error_field', models.CharField(max_length=50)),
                ('error_message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'import_error',
                'verbose_name': 'Import Error Log',
                'verbose_name_plural': 'Import Error Logs',
            },
        ),
    ]
